from fastapi import APIRouter

from app.api.routes import alerts, auth, autonomous_portfolios, companies, dashboard, decisions, education, entity_resolution, evidence_intelligence, events, executive_intelligence, factors, knowledge_extraction, knowledge_graph, market, mentor, missions, multi_agent_consensus, news, portfolios, research, research_agent, research_projects, research_sessions, research_trust_index, system, watchlists

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(education.router, prefix="/education", tags=["education"])
api_router.include_router(knowledge_graph.router, prefix="/knowledge-graph", tags=["knowledge-graph"])
api_router.include_router(knowledge_extraction.router, prefix="/knowledge-graph", tags=["knowledge-extraction"])
api_router.include_router(entity_resolution.router, prefix="/knowledge-graph", tags=["entity-resolution"])
api_router.include_router(evidence_intelligence.router, prefix="/evidence-intelligence", tags=["evidence-intelligence"])
api_router.include_router(research_trust_index.router, prefix="/research-trust-index", tags=["research-trust-index"])
api_router.include_router(multi_agent_consensus.router, prefix="/multi-agent-consensus", tags=["multi-agent-consensus"])
api_router.include_router(executive_intelligence.router, prefix="/executive-intelligence", tags=["executive-intelligence"])
api_router.include_router(missions.router, prefix="/missions", tags=["missions"])
api_router.include_router(mentor.router, prefix="/mentor", tags=["mentor"])
api_router.include_router(research.router, prefix="/research", tags=["research"])
api_router.include_router(research_agent.router, prefix="/research-agent", tags=["research-agent"])
api_router.include_router(research_projects.router, prefix="/research-projects", tags=["research-projects"])
api_router.include_router(research_sessions.router, tags=["research-sessions"])
api_router.include_router(news.router, prefix="/news", tags=["news"])
api_router.include_router(market.router, prefix="/market", tags=["market"])
api_router.include_router(watchlists.router, prefix="/watchlists", tags=["watchlists"])
api_router.include_router(portfolios.router, prefix="/portfolios", tags=["portfolios"])
api_router.include_router(autonomous_portfolios.router, prefix="/portfolios", tags=["portfolio-intelligence"])
api_router.include_router(alerts.router, prefix="/alerts", tags=["alerts"])
api_router.include_router(companies.router, prefix="/companies", tags=["companies"])
api_router.include_router(factors.router, prefix="/factors", tags=["factors"])
api_router.include_router(events.router, prefix="/events", tags=["events"])
api_router.include_router(decisions.router, prefix="/decisions", tags=["decisions"])
api_router.include_router(system.router, prefix="/system", tags=["system"])
