from fastapi import APIRouter

from app.api.routes import advanced_alerts, alerts, auth, autonomous_portfolios, companies, dashboard, decisions, education, entity_resolution, evidence_intelligence, events, executive_intelligence, factors, knowledge_extraction, knowledge_federation, knowledge_graph, knowledge_memory, knowledge_quality, market, market_learning, market_learning_evidence, market_learning_mastery, market_learning_portfolio, market_learning_progress, market_learning_roadmap, market_mentor, market_simulator, mentor, missions, multi_agent_consensus, news, portfolios, research, research_agent, research_conclusion_defense_review, research_conclusion_export_packet, research_conclusion_readiness, research_conclusion_workspace, research_evidence, research_evidence_audit_packet, research_evidence_provenance, research_follow_up_tracker, research_governance_dashboard, research_governance_digest, research_orchestration, research_planning, research_projects, research_sessions, research_trust_index, system, watchlists

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(education.router, prefix="/education", tags=["education"])
api_router.include_router(knowledge_graph.router, prefix="/knowledge-graph", tags=["knowledge-graph"])
api_router.include_router(knowledge_extraction.router, prefix="/knowledge-graph", tags=["knowledge-extraction"])
api_router.include_router(entity_resolution.router, prefix="/knowledge-graph", tags=["entity-resolution"])
api_router.include_router(knowledge_memory.router, prefix="/knowledge-memory", tags=["knowledge-memory"])
api_router.include_router(knowledge_federation.router, prefix="/knowledge-federation", tags=["knowledge-federation"])
api_router.include_router(knowledge_quality.router, prefix="/knowledge-quality", tags=["knowledge-quality"])
api_router.include_router(research_planning.router, prefix="/research-planning", tags=["research-planning"])
api_router.include_router(evidence_intelligence.router, prefix="/evidence-intelligence", tags=["evidence-intelligence"])
api_router.include_router(research_evidence_provenance.router, prefix="/research-evidence-provenance", tags=["research-evidence-provenance"])
api_router.include_router(research_evidence_audit_packet.router, prefix="/research-evidence-audit", tags=["research-evidence-audit"])
api_router.include_router(research_follow_up_tracker.router, prefix="/research-follow-up", tags=["research-follow-up"])
api_router.include_router(research_conclusion_readiness.router, prefix="/research-conclusion-readiness", tags=["research-conclusion-readiness"])
api_router.include_router(research_conclusion_workspace.router, prefix="/research-conclusions", tags=["research-conclusions"])
api_router.include_router(research_conclusion_export_packet.router, prefix="/research-conclusion-export", tags=["research-conclusion-export"])
api_router.include_router(research_conclusion_defense_review.router, prefix="/research-conclusion-defense", tags=["research-conclusion-defense"])
api_router.include_router(research_governance_dashboard.router, prefix="/research-governance-dashboard", tags=["research-governance-dashboard"])
api_router.include_router(research_governance_digest.router, prefix="/research-governance-digest", tags=["research-governance-digest"])
api_router.include_router(research_trust_index.router, prefix="/research-trust-index", tags=["research-trust-index"])
api_router.include_router(multi_agent_consensus.router, prefix="/multi-agent-consensus", tags=["multi-agent-consensus"])
api_router.include_router(research_orchestration.router, prefix="/research-orchestration", tags=["research-orchestration"])
api_router.include_router(executive_intelligence.router, prefix="/executive-intelligence", tags=["executive-intelligence"])
api_router.include_router(missions.router, prefix="/missions", tags=["missions"])
api_router.include_router(mentor.router, prefix="/mentor", tags=["mentor"])
api_router.include_router(research.router, prefix="/research", tags=["research"])
api_router.include_router(research_agent.router, prefix="/research-agent", tags=["research-agent"])
api_router.include_router(research_projects.router, prefix="/research-projects", tags=["research-projects"])
api_router.include_router(research_sessions.router, tags=["research-sessions"])
api_router.include_router(research_evidence.router, tags=["research-evidence"])
api_router.include_router(news.router, prefix="/news", tags=["news"])
api_router.include_router(market.router, prefix="/market", tags=["market"])
api_router.include_router(market_simulator.router, prefix="/market-simulator", tags=["market-simulator"])
api_router.include_router(market_mentor.router, prefix="/market-simulator", tags=["market-simulator-mentor"])
api_router.include_router(market_learning.router, prefix="/market-simulator", tags=["market-simulator-learning"])
api_router.include_router(market_learning_progress.router, prefix="/market-simulator", tags=["market-simulator-learning"])
api_router.include_router(market_learning_evidence.router, prefix="/market-simulator", tags=["market-simulator-learning"])
api_router.include_router(market_learning_portfolio.router, prefix="/market-simulator", tags=["market-simulator-learning"])
api_router.include_router(market_learning_roadmap.router, prefix="/market-simulator", tags=["market-simulator-learning"])
api_router.include_router(market_learning_mastery.router, prefix="/market-simulator", tags=["market-simulator-learning"])
api_router.include_router(watchlists.router, prefix="/watchlists", tags=["watchlists"])
api_router.include_router(portfolios.router, prefix="/portfolios", tags=["portfolios"])
api_router.include_router(autonomous_portfolios.router, prefix="/portfolios", tags=["portfolio-intelligence"])
api_router.include_router(alerts.router, prefix="/alerts", tags=["alerts"])
api_router.include_router(advanced_alerts.router, prefix="/advanced-alerts", tags=["advanced-alerts"])
api_router.include_router(companies.router, prefix="/companies", tags=["companies"])
api_router.include_router(factors.router, prefix="/factors", tags=["factors"])
api_router.include_router(events.router, prefix="/events", tags=["events"])
api_router.include_router(decisions.router, prefix="/decisions", tags=["decisions"])
api_router.include_router(system.router, prefix="/system", tags=["system"])
